from datetime import datetime

from sqlalchemy import DateTime, Float, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.database.database import Base


class Event(Base):
    """
    Stores filesystem events detected by RDRS.
    """

    __tablename__ = "events"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    event_type: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
    )

    file_path: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    timestamp: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.now,
        nullable=False,
    )

    extension: Mapped[str] = mapped_column(
        String(20),
        default="",
    )

    old_path: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )


class ProcessSnapshot(Base):
    """
    Stores snapshots of running processes.
    """

    __tablename__ = "processes"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    pid: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )

    name: Mapped[str] = mapped_column(
        String(255),
        default="",
    )

    cpu_percent: Mapped[float] = mapped_column(
        Float,
        default=0.0,
    )

    memory_percent: Mapped[float] = mapped_column(
        Float,
        default=0.0,
    )

    disk_writes: Mapped[int] = mapped_column(
        Integer,
        default=0,
    )

    executable_path: Mapped[str] = mapped_column(
        Text,
        default="",
    )

    parent_pid: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )

    parent_name: Mapped[str] = mapped_column(
        String(255),
        default="",
    )

    timestamp: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.now,
        nullable=False,
    )


class Score(Base):
    """
    Stores risk scores calculated by RDRS.
    """

    __tablename__ = "scores"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    event_id: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )

    process_id: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )

    score: Mapped[float] = mapped_column(
        Float,
        default=0.0,
    )

    reason: Mapped[str] = mapped_column(
        Text,
        default="",
    )

    timestamp: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.now,
        nullable=False,
    )


class Alert(Base):
    """
    Stores alerts generated by RDRS.
    """

    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    severity: Mapped[str] = mapped_column(
        String(20),
        default="LOW",
    )

    message: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    timestamp: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.now,
        nullable=False,
    )


class Incident(Base):
    """
    Stores security incidents detected by RDRS.
    """

    __tablename__ = "incidents"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    description: Mapped[str] = mapped_column(
        Text,
        default="",
    )

    severity: Mapped[str] = mapped_column(
        String(20),
        default="LOW",
    )

    status: Mapped[str] = mapped_column(
        String(20),
        default="OPEN",
    )

    timestamp: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.now,
        nullable=False,
    )